[project]
name = "pairpong"
version = "0.0.1"
authors = []
description = "Crypto Pong Battle - A blockchain-based gaming platform"
telemetry = false

[project.requirements]
# No external requirements

[contracts.battle-leaderboard-v4]
path = "contracts/battle-leaderboard-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip-009-nft-trait-v4]
path = "sips/sip-009-nft-trait-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.battle-nft-v4]
path = "contracts/battle-nft-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.battle-prediction-v4]
path = "contracts/battle-prediction-v4.clar"
clarity_version = 2
epoch = 2.5