[project]
name = "pairpong"
version = "0.0.1"
authors = []
description = "Crypto Pong Battle - A blockchain-based gaming platform"
telemetry = false

[project.requirements]
# No external requirements

[contracts.battle-leaderboard]
path = "contracts/battle-leaderboard.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip-009-nft-trait]
path = "sips/sip-009-nft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.battle-nft]
path = "contracts/battle-nft.clar"
clarity_version = 2
epoch = 2.5

[contracts.battle-betting]
path = "contracts/battle-betting.clar"
clarity_version = 2
epoch = 2.5