[project]
name = "pairpong"
version = "0.0.1"
epoch = "2.3"
clarity-version = "2"
requirements = []

[contracts]
battle-leaderboard = "src/contracts/battle-leaderboard.clar"
sip-009-nft-trait = "src/sips/sip-009-nft-trait.clar"
battle-nft = "src/contracts/battle-nft.clar"
battle-betting = "src/contracts/battle-betting.clar"

[repl]
costs = true
parser = 0

[network.testnet]
cost-limit = 100000000

[network.mainnet]
cost-limit = 100000000